### ISSUE TITLE
Migracion/Modelo Usuarios

### ISSUE THREAD

**Issue by gabymq** [gabymq/apoya.me#4]
## Tarea
Crear migraciones y  modelos que deberan ser de acuerdo a las especificaciones de diagrama ER creado en el issue #2 

## Productos esperados
- [x] Migraciones
- [x] Modelos

**Comment by virgenherrera** [comment]
## Acerca de las migraciones
@gabymq te recomiendo que cheques la documentación de [sequelize-cli](http://docs.sequelizejs.com/en/v3/docs/migrations/) donde habla sobre las migraciones, y como crearlas; Ya que en este punto el proyecto es virgen, es recomendable que crees un modelos pues, de esa manera, creas el modelo y la migración, y no tengas que hacer tantas cosas; tambien te dejo una liga con donde podrás hallar los [tipos de datos](http://docs.sequelizejs.com/en/v3/docs/models-definition/) disponibles en sequelize. 


## Te dejare un ejemplo aquí
este comando te crearía la migración y el modelo inherente a el:
`sequelize model:create id:int,nombre:string,apellido:string,fecha_nacimiento:date`

lo anterior crearia una migracion y un modelo con los campos:

- id (INT)
- nombre (STRING)
- apellido (STRING)
- fecha_nacimiento (DATE)
