### ISSUE TITLE
Configuracion

### ISSUE THREAD

**Issue by gabymq** [gabymq/apoya.me#5]
Configurar el proyecto de acuerdo con el workflow

**Comment by virgenherrera** [comment]
# Archivo .editorconfig
@gabymq te parece esta config para el .editorconfig?

#editorconfig.org
root = true

[*]
charset = utf-8
end_of_line = lf
trim_trailing_whitespace = true
insert_final_newline = true

[www]
indent_style = tab
indent_size = 4

[*.{js,ts,jsx,coffee,pug}]
indent_style = tab
indent_size = 4


[*.json]
indent_style = space
indent_size = 2

**Comment by gabymq** [comment]
Si esta bien, lo creare en la raiz @virgenherrera

**Comment by gabymq** [comment]
## Dependencias del Proyecto
express
pug
sequelize
pg
pg-hstore
jsonwebtoken
forever

## Dependencias de Desarrollo
sequelize-cli
nodemon

## Notas
### 1
Fueron instalados  de la siguiente manera:
`npm i -S sequelize pg pg-hstore jsonwebtoken forever`
`npm i -D sequelize-cli nodemon`

### 2
Es mas sencillo trabajar en la consola instalando estas librerias de manera global
`npm i -g sequelize-cli nodemon`
